updating docs for bit functions and json table
dolthub/docs pull request #855
Opened 2022-08-17 19:21 UTC by JCOR11599

i didn't forget this time :)

2022-08-17 19:34 UTC, timsehn approved these changes
Just the one comment on `BIT_OR()`  formatting looking weird.

2022-08-17 19:34 UTC, timsehn commented on content/reference/sql/sql-support/expressions-functions-operators.md
> +| `BIT_OR()`                        | ✅         | `\                                                                |` is supported
This is weird. You sure it's gonna render fine?

2022-08-17 19:37 UTC, jycor commented on content/reference/sql/sql-support/expressions-functions-operators.md
> +| `BIT_OR()`                        | ✅         | `\                                                                |` is supported
not sure how that got there, will fix

2022-08-17 21:29 UTC, timsehn requested changes

2022-08-17 21:29 UTC, timsehn commented on content/reference/sql/sql-support/expressions-functions-operators.md
>  ## Aggregate Functions
Check this section. These functions are listed twice :-(

2022-08-18 22:22 UTC, timsehn approved these changes
LGTM. Ship it.

2022-08-18 22:24 UTC, merged